# Define build-time variables
ARG NODE_VERSION=22-alpine
ARG WORKDIR=/usr/src/app

# Define environment variables
ARG PORT=80
ARG OPENAI_API_KEY
ARG CLAUDE_API_KEY
ARG IPS

# Stage 1: Build
FROM node:${NODE_VERSION} as build

WORKDIR ${WORKDIR}

COPY package*.json ./

RUN npm install

COPY ./ ./

RUN npm run build

# Stage 2: Run
FROM node:${NODE_VERSION}

RUN apk update && apk upgrade && apk add curl

USER node

WORKDIR ${WORKDIR}

COPY --chown=node:node --from=build ${WORKDIR} .
COPY --chown=node:node .env .env

# Set environment variables
ENV PORT=${PORT}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV CLAUDE_API_KEY=${CLAUDE_API_KEY}
ENV IPS=${IPS}

EXPOSE ${PORT}

HEALTHCHECK CMD curl -f http://localhost:${PORT}/healthz || exit 1

CMD ["npm", "run", "start"]
