FROM golang:1.24-alpine

RUN apk --no-cache add curl

ENV APP_ENV=production

WORKDIR /app

COPY . .

RUN go build -o commit .

EXPOSE 80

HEALTHCHECK CMD curl -f http://localhost/healthz || exit 1

CMD ["./commit"]
